README.md
Using this script on [the following page](https://github.com/orgs/nodejs/teams/modules/members),
helps members page to be sync each update.
```js
// per each page
const members = JSON.parse(localStorage.getItem('members') || '[]');
document.querySelectorAll('a.f4').forEach(a => {
const name = a.textContent.trim();
const slug = a.nextElementSibling ?
a.nextElementSibling.textContent.trim() : name;
const href = a.href;
members.push({name, slug, href});
});
localStorage.setItem('members', JSON.stringify(members));
// sort them out after all pages
members.sort((a, b) => {
const aSlug = a.slug.toLowerCase();
const bSlug = b.slug.toLowerCase();
return aSlug < bSlug ? -1 : 1;
});
// generate markdown
console.log(members.map(
m => `* [${m.name}](${m.href}) @${m.slug}`
).join('\n')); …
```
=> Update Team Members List

doc/meetings/2017-02-14.md
@nodejs/modules should we wait until the next meeting to approve / land this?
=> doc: add meeting notes for Feb 14 2018

GOVERNANCE.md
Per: https://docs.google.com/document/d/17T8ZeF2mUPffiDvulqd_HqD_JrTNaf8ch2dFT1hMfD0/edit?disco=AAAABp_P_B0
=> Document quorum required in order to merge PRs

GOVERNANCE.md, README.md
* sync with with ncu-team sync
> \#31 should have added @thelarkinn to the members list. It was closed
for unrelated reasons but we never got Sean on the list.
* s/Modules Team Members/Members
* remove hyperlink from "Members" header
>The original hyperlink lead to:
>
>https://github.com/orgs/nodejs/teams/modules/members
>
>Which is only accessible to people in the Node.js org afaict. The
member list is in the doc, the link is likely to just confuse folks.
* update ncu-team meta data
>It now can inline Members and Observers. This is connected to the ACL
in github. The Observers header is currently commented out.
* fix link in governance to membership list
=> doc: update members list

doc/meetings/2018-04-11.md
Refs: https://github.com/nodejs/modules/issues/61
refs: https://docs.google.com/document/d/1qS0_Cwfgy3hw_dOuRoiEtMtdL_QrWPcFJQrRQrXth6M/edit?usp=sharing
Refs: https://www.youtube.com/watch?v=98oCvKU7c8k
=> doc: add meeting notes for 2018-04-11

GOVERNANCE.md
This changes the special PR merging exemption for Errata and Editorial changes to be a general "Special Exemptions to the PR landing process", which has been updated to include meeting minutes & team updates via `ncu-sync`.
This is done so as to not consume time in meetings approving minutes.
This _could_ be left for the next meeting. (PR Made during the meeting of April the 25th.)
=> governance: introduce PR exemptions for minutes

doc/meetings/2018-04-25.md
=> doc: add 2018-04-25 notes

GOVERNANCE.md
Our current process for opening a PR to request membership was
implemented before we started using ncu-sync to keep the membership
list up to date. With this is mind I think it makes more sense
to have new members make a request to join via issue rather than
PR.
=> governance: s/pull request/issue for new members

README.md
hey folks. o/
I'm working on defining a common base for user land loaders. My goal is to make it easy to make loaders that speed up node startup time, and work well together. 
I'm excited to contribute and it was great meeting some of you at the collab summit.
=> add @soldair to observers

doc/plan-for-new-modules-implementation.md
Per the discussion in our last meeting, @MylesBorins, @smotaal and @jdalton and I drafted a new Phase 2 document.
https://github.com/GeoffreyBooth/modules/blob/phase-2/doc/plan-for-new-modules-implementation.md#phase-2
=> Doc: Phase 2 for new modules implementation

doc/plan-for-new-modules-implementation.md
I'd like us to add the format distinction question to the Phase 2 process.
It seems important to finally tackle this one and get some movement on solutions here.
This includes any top-level --module flag, as well as internal imports to CommonJS for switching from ESM loading to CJS loading.
=> Add format distinction to phase 2

GOVERNANCE.md
Be explicit that if a new members has requested to join and the issue has no objections that can attend the meeting where their membership is approved
=> governance: be explicit about meetings new members can join

README.md, doc/plan-for-new-modules-implementation.md
This PR adds links from our new modules implementation plan (with the phases) to the proposals that have been drafted so far; and a link from the main README to the new modules implementation plan and repo.
=> Add links to docs

doc/plan-for-new-modules-implementation.md
As agreed upon in Dec 19th meeting
=> doc: update stage 2 regarding dynamic modules

doc/plan-for-new-modules-implementation.md
Building off of the [implementation](https://github.com/nodejs/modules/issues/248#issuecomment-455187343) of the [“Package Exports” proposal](https://github.com/jkrems/proposal-pkg-exports) and the [“File Specifier Resolution” proposal](https://github.com/GeoffreyBooth/node-import-file-specifier-resolution-proposal), I think we can move on to figuring out how to support ESM input via `--eval`, STDIN and extensionless files.
Anyone interested in forming a small group to hash these out?
=> --eval, STDIN, and extensionless files

doc/meetings/2019-01-16.md
Refs: https://github.com/nodejs/modules/issues/248
=> doc: 2019-01-16 notes

doc/meetings/2019-01-30.md
Refs: https://github.com/nodejs/modules/issues/258
=> doc: 2019-01-30 notes

RESOURCES.md
Mostly
* ~transpiler -> compiler~
* aligned the phrasing between Babel & TypeScript (they both support the same interop mode)
* I generally consider Reify and `@std/esm` to be closer to runtime tools than compilers.
Let me know if there are any objections here.
=> Corrected categorization and language for RESOURCES.md

GOVERNANCE.md
Current rules only apply to this repo not the fork. Makes things clearer and expands on the types of changes that don't require meetings to be approved.
=> governance: explicit rules for modules-lkgr fork

doc/plan-for-new-modules-implementation.md
Readable version: https://github.com/GeoffreyBooth/modules/blob/update-roadmap/doc/plan-for-new-modules-implementation.md. The diff is a mess so you might want to just read that side-by-side with the [current version](https://github.com/nodejs/modules/blob/master/doc/plan-for-new-modules-implementation.md).
@MylesBorins and I worked together to update our new implementation’s plan per [the Google doc where the team has noted our current status](https://docs.google.com/document/d/1DSWrdV1fzXvlOdTZ5MngDX7v6CU4ZUheJ7ysOZ2uK0w/edit?ts=5c63dc98). In particular:
- The “How will we get from where we are to Phase 1” section has been moved to a new Phase 0, to reflect that it’s already done and was a precursor to our Phase 1.
- The end of Phase 2 corresponds with replacing the existing …
=> Revise road map per current status

doc/plan-for-new-modules-implementation.md
Update per today’s meeting, includes #287.
=> Update Phase 2 file extension/directory index searching plan

doc/plan-for-new-modules-implementation.md
This PR moves the new loaders work to Phase 3.
This is assuming https://github.com/nodejs/ecmascript-modules/pull/47 to include _a_ solution in the mean time.
I've worked with @bmeck to understand where the current implementation is, and did consider driving this work over the next week to get something together, but we should probably try to be sensible about the design process here.
=> Move loaders to phase 3

GOVERNANCE.md
This PR updates the governance doc to reflect what was discussed in the prior meeting #302.
The previous heading which "Merging PRs into this Repository or nodejs/ecmascript-modules" has been replaced with a "Pull Requests" and broken down into:
1. Merging PRs into nodejs/node
2. Merging PRs into nodejs/ecmascript-modules
3. Special Exemptions for Pull Requests
This new structure is my best effort to adhere to the existing wording and still be able to detail the general discussion points based on the minutes and the recording. Please note that I found it rather difficult to distill all this and greatly welcome your help improving on this before landing.
=> Governance: "Pull Requests" post Phase 2 upstream

doc/plan-for-new-modules-implementation.md
Please let me know if I missed anything. Phase 3 didn’t really change per today’s meeting, as far as I can tell; the updates were mostly errata.
It felt weird to add the champions to that doc so I thought I’d add them here. Personally I’d also like to know who would be interested in contributing to each feature’s development, either by writing code or by attending breakout meetings, so if that describes you please edit this comment to add your name:
- **Loaders**
Co-Champions: @guybedford, @SMotaal, @devsnek
Interested: @bmeck
- **Dual CommonJS/ESM Packages**
Co-Champions: @GeoffreyBooth, @ljharb 
Interested: @weswigham, @guybedford 
- **Easier `require` in ESM**
Co-Champions: @MylesBorins 
Interested: @Fishrock123 
- **Package path maps**
Co-Champions: @jkrems 
Interested: …
=> Update roadmap per 2018-04-24 meeting

doc/meetings/2019-04-24.md
Refs: https://github.com/nodejs/modules/issues/317
=> doc: 2019-04-24 notes

doc/plan-for-new-modules-implementation.md
This updates the roadmap with where I think we are now. We can discuss the particulars in the next meeting.
Readable version: https://github.com/nodejs/modules/blob/phase-3-update/doc/plan-for-new-modules-implementation.md#phase-3-path-to-stability-removing—experimental-modules-flag
=> Phase 3 update

doc/plan-for-new-modules-implementation.md
=> Updates per 2019-06-19 meeting

doc/meetings/2019-08-14.md, doc/meetings/2019-08-28.md
Refs: https://github.com/nodejs/modules/issues/370
Refs: https://github.com/nodejs/modules/issues/376
=> doc: august meeting notes

doc/plan-for-new-modules-implementation.md
https://github.com/nodejs/modules/pull/387/files?short_path=efa67e9#diff-efa67e9109ca1a93520741c28eb913c9
=> Roadmap update per 2019-09-25 meeting

doc/plan-for-new-modules-implementation.md
Minor updates for the conditional exports PRs that were merged in.
I plan to update again with the overall unflagging once it’s actually released, so that people don’t read that the unflagging has already happened but then they can’t download a version of Node with that. Should only be a few more days it seems like.
=> Update roadmap for conditional exports

doc/plan-for-new-modules-implementation.md
So eight months ago I opened https://github.com/nodejs/node/pull/27808 to add a utility method to Node core for detecting if JavaScript source code contained ES module syntax. That PR is still open and it’s not looking likely that it will be merged anytime soon, so I’m thinking of closing it. I might release the code as a standalone NPM package.
The PR’s `containsModuleSyntax` method wasn’t all that useful on its own, and wasn’t used by Node core; it was created to be a dependency for potential Node core features like `--input-type=auto`. Are will still planning on implementing `--input-type=auto`, or any other feature that might rely on `containsModuleSyntax`?
If not, I can close the PR and mark this roadmap item as done/tabled, unless anyone has any objections or reasons we might want …
=> Table source type detection

README.md, doc/features.md, doc/plan-for-new-modules-implementation.md, doc/use-cases.md
Resolves https://github.com/nodejs/modules/issues/473. This archives out-of-date content and puts on our README the most important information that most visitors to this repo are likely looking for.
=> Rewrite readme

doc/meetings/2020-06-17.md
refs: https://github.com/nodejs/modules/issues/528
closes: https://github.com/nodejs/modules/issues/528
refs: https://docs.google.com/document/d/1FLK3nkCpxF6D-JFuoZlGpovF0lpSQ_8TP3wini6FsB0/edit
=> docs: Minutes for 2020-06-17

README.md
Ran `ncu-team sync` after cleanup in https://github.com/nodejs/admin/issues/513. Apparently, it's been a while since the team list has been updated.
=> chore: update teams in README.md

README.md
Update team list.
Manually re-added Zack Schuster's name.
=> chore: update README.md with `ncu-team sync README.md`

doc/meetings/2020-07-29.md
Closes https://github.com/nodejs/modules/issues/536
=> Add meeting notes for 2020-07-29

README.md
I would like to participate in the module group meetings.
I'm interested in the ESM specification and the emerging import map standard.
=> Add Doron Tsur as observer

doc/meetings/2020-10-07.md, doc/meetings/2020-10-21.md
Closes: https://github.com/nodejs/modules/issues/557
Closes: https://github.com/nodejs/modules/issues/563
=> doc: update missing notes
