nodejs/modules

README.md
i think this should probably be under our domain as well
=> add vm modules implementation to our work

RESOURCES.md
only a few things added, mainly to kick things off. i'm sure there's a bajillion resources that could/should be added.
no real overriding principle here besides "this is related to nodejs esm work" & "i think making it more accessible would help people"
=> add RESOURCES.md

RESOURCES.md
As suggested in PR #12 it could be interesting
to investigate or share code and knowledge
about CommonJS in ESM and/or vice-versa
=> Add Prior Art Section

GOVERNANCE.md
Corrected detail about where we host meetings.
=> doc: s/Google Hangouts/Zoom

GOVERNANCE.md
=> Revert "doc: s/Google Hangouts/Zoom"

doc/meetings/2018-02-28.md
@nodejs/modules please review. If you attended the meeting and your name is not in the list please comment and I'll add it
=> doc: add meeting notes for 2018-02-28

README.md
=> Add tzmanics as an observer

README.md
Unfortunately, I haven't been able to dedicate much time to Modules. This should hopefully make it easier to reach quorum.
=> Move @TimothyGu to observers

README.md
This PR is to request @GeoffreyBooth be moved to a member. I believe his contributions to discussions and meetings warrants the move.
=> Move Geoffrey Booth to member.

README.md
This adds @zenparsing as an observer.
=> Add Kevin Smith as an observer.

doc/meetings/2018-05-23.md
Please feel free to push changes or updates
=> doc: 5-23 meeting notes

README.md
Sorry it's a French thing, it's looking inconsistent/weird.
=> Consistent last name formatting 

doc/meetings/2018-07-11.md
copied from https://docs.google.com/document/d/1m1yCbb5A6t8KGy9Ov33I7YNKR_fxMPCIJLC3HymGLS8/edit
=> doc: july 11 2018 meeting notes

README.md
=> chore: update member list with ncu

doc/meetings/2018-07-18.md, doc/meetings/2018-08-01.md
=> doc: add meetings notes

README.md
Closes: https://github.com/nodejs/modules/issues/176
=> doc: sync members with ncu-team

doc/meetings/2018-08-15.md, doc/meetings/2018-08-29.md
=> doc: more august notes

doc/meetings/2018-09-12.md
=> doc: 2018.09.12 notes

README.md
=> doc: update members with ncu-team sync

doc/meetings/2018-10-03.md, doc/meetings/2018-10-24.md
=> doc: october meeting notes

doc/meetings/2018-11-21.md
Refs: https://github.com/nodejs/modules/issues/226
=> doc: add notes for 2018-11-21

doc/meetings/2018-12-05.md
Refs: https://docs.google.com/document/d/1b5aA1jiYRSjjvjIwU2pt1FK7OiaR5EMLmM72E9oR9pI/edit
=> doc: notes for 2018-12-05

doc/meetings/2019-02-13.md
Refs: https://github.com/nodejs/modules/issues/266
=> doc: add notes for 2019-02-13

README.md
Updated based on github IAM roles
=> doc: update members list with ncu-sync

doc/meetings/2019-02-20.md
Refs: https://github.com/nodejs/modules/issues/270
=> doc: 2019-02-20 Notes

doc/meetings/2019-02-27.md
Refs: https://github.com/nodejs/modules/issues/276
=> doc: 2019-02-27 meeting notes

doc/meetings/2019-03-13.md
Refs: https://github.com/nodejs/modules/issues/292
=> doc: add notes for 2019-03-13

doc/meetings/2019-03-27.md
Refs: https://github.com/nodejs/modules/issues/302
=> doc: 2019-03-27 notes

doc/meetings/2019-04-10.md
Refs: https://github.com/nodejs/modules/issues/310
=> doc: meeting notes for 2019-04-10

doc/meetings/2019-03-04.md
Meeting notes for 2019-03-04 meeting: https://github.com/nodejs/modules/issues/282.
=> doc: 2019-03-04 meeting notes

doc/plan-for-new-modules-implementation.md
=> doc: update links

doc/meetings/2019-05-22.md
Refs: https://github.com/nodejs/modules/issues/332
=> doc: 2019-05-22 notes

README.md
As requested in #363.
Closes #363.
=> Add @jamiebuilds and @devongovett as observers

doc/meetings/2019-07-17.md
This includes the meeting notes for the meeting at https://github.com/nodejs/modules/issues/349.
=> Add meeting notes for 07/17

doc/announcement.md
This PR updates the announcement file in this repo to match [the final text that was published to Medium](https://medium.com/@nodejs/announcing-a-new-experimental-modules-1be8d2d6c2ff).
I find the file in this repo to be a better document to link to, both because I can link directly to subheadings and also because code looks like `code`, not just italics.
There are no editorial changes other than those which were made when publishing to Medium. The new text should exactly match what it is on Medium (aside from being in Markdown and not HTML).
=> doc: update announcement to match final published text

doc/meetings/2019-10-09.md
=> doc: Minutes for 2019-10-09

README.md
I'm not going to actively participate in my free time.
=> doc: move fishrock123 to observer

doc/meetings/2019-09-11.md, doc/meetings/2019-09-25.md
Refs: https://github.com/nodejs/modules/issues/383
Refs: https://github.com/nodejs/modules/issues/386
=> doc: add missing sept notes

README.md
=> doc: update membership list

README.md
=> doc: update members

README.md, doc/plan-for-new-modules-implementation.md
Updated per our consensuses reached in today’s meeting.
https://github.com/nodejs/modules/pull/416/files?short_path=efa67e9#diff-efa67e9109ca1a93520741c28eb913c9
=> Roadmap update per 2019-10-30 meeting

doc/meetings/2019-10-30.md
Meeting issue: https://github.com/nodejs/modules/issues/408
=> Add meetings notes for 2019-10-30

doc/meetings/2019-11-06.md
Refs: https://www.youtube.com/watch?v=0uQOL7j2Fz0
Refs: https://github.com/nodejs/modules/issues/423
Refs: https://docs.google.com/document/d/1jmV36-0S8ZH4wXWpXTMfpsc83OsuYh4KCCEzJ2Gu9TM/edit
Closes: https://github.com/nodejs/modules/issues/423
=> docs: notes for 2019-11-06

README.md
The topic I am most interested in is the loader specification and would like to get more involved with moving it closer towards stability. I have already done [some research in the form of a PR](https://github.com/nodejs/node/pull/29819) that may contribute to its stabilization. Might as well make it official since I have been observing. 😉
=> Add Derek Lewis as an observer

doc/meetings/2019-12-18.md
Refs: https://github.com/nodejs/modules/issues/455
Refs: https://docs.google.com/document/d/107-EWDmaUN5XCHNzme6h5AYfl1L3J-ZbgZSq7bqWC8E/edit
Closes: https://github.com/nodejs/modules/issues/455
=> docs: notes for 2019-12-18

doc/meetings/2020-01-08.md
Refs: https://github.com/nodejs/modules/issues/461
Refs: https://docs.google.com/document/d/1RwdeqHV9oJBBafcAajWZQ0eCnzcMNSo-dQGN1WeEszY/
Closes: https://github.com/nodejs/modules/issues/461
=> doc: notes for 2020-01-08

doc/meetings/2020-01-15.md
Closes https://github.com/nodejs/modules/issues/466
=> Add meeting notes for 2020-01-15

doc/meetings/2020-02-12.md
Fixes https://github.com/nodejs/modules/issues/483
=> Add meeting notes for 2020-02-12

doc/meetings/2020-02-26.md
Refs: #489 
Refs: https://docs.google.com/document/d/1Evh1h_SAq7VnfXJlt5V8-HX5an6JstVdRE9IkowxU5E/edit
Closes: #489
=> doc: Meetings notes 2020-02-26

doc/meetings/2020-04-22.md
Refs: #504  
Refs: https://docs.google.com/document/d/1G1coLWXsCPPWsfkgbYR0aXvmSRMoaJIz-ndpVk_2Nlc/edit
Closes: #504
=> doc: Meeting notes 2020-04-22

doc/meetings/2020-05-06.md
refs: #510
refs: https://docs.google.com/document/d/1Iw0xXfc080uQoarPQvm6MuCjUdIX6Yhv83MjgiXV_Pw/edit
closes: #510
=> doc: Meeting notes 2020-05-06

doc/meetings/2020-05-20.md
refs: #510 
refs: https://docs.google.com/document/d/1XUBqEtPDwsgOgjrsoyacQhXHpTTdMyWAnEiwoZcDh4o/edit
closes: #510
=> doc: Meeting notes 2020-05-20

doc/meetings/2020-07-15.md, doc/meetings/2020-08-12.md, doc/meetings/2020-08-26.md, doc/meetings/2020-09-09.md
Closes: https://github.com/nodejs/modules/issues/532
Closes: https://github.com/nodejs/modules/issues/543
Closes: https://github.com/nodejs/modules/issues/548
Closes: https://github.com/nodejs/modules/issues/552
=> doc: add missing meeting notes
